//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_permiso
    {
        public int id { get; set; }
        public string Modulo { get; set; }
        public int Rol { get; set; }
        public int Permiiso { get; set; }
        public Nullable<int> Accion { get; set; }
    
        public virtual Acciones Acciones { get; set; }
        public virtual Modulos Modulos { get; set; }
        public virtual Tb_Permiso_Denegado_Roles Tb_Permiso_Denegado_Roles { get; set; }
        public virtual Tb_Rol_Usuarios Tb_Rol_Usuarios { get; set; }
    }
}
