//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Abonos
    {
        public int Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Credito { get; set; }
        public double Valor { get; set; }
        public string Estado { get; set; }
    
        public virtual Tb_Creditos Tb_Creditos { get; set; }
    }
}
