//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Creditos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Creditos()
        {
            this.Tb_Abonos = new HashSet<Tb_Abonos>();
        }
    
        public int Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
        public int Numero_Pagare { get; set; }
        public Nullable<double> Cuota_inicial { get; set; }
        public double Total_Adeudado { get; set; }
        public int Venta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Abonos> Tb_Abonos { get; set; }
        public virtual Tb_Estados Tb_Estados { get; set; }
        public virtual Tb_ventas Tb_ventas { get; set; }
    }
}
