//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cuotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cuotas()
        {
            this.Tb_AbonosCuotas = new HashSet<Tb_AbonosCuotas>();
            this.Tb_AbonosCuotas1 = new HashSet<Tb_AbonosCuotas>();
        }
    
        public int Codigo { get; set; }
        public int Financiacion { get; set; }
        public int NumeroCuotas { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaLimite { get; set; }
        public double ValorCuotas { get; set; }
        public int CuotasAPagar { get; set; }
        public System.DateTime FechaAPagar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_AbonosCuotas> Tb_AbonosCuotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_AbonosCuotas> Tb_AbonosCuotas1 { get; set; }
        public virtual Tb_Financiacion Tb_Financiacion { get; set; }
        public virtual Tb_Financiacion Tb_Financiacion1 { get; set; }
        public virtual Tb_Financiacion Tb_Financiacion2 { get; set; }
    }
}
