//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Configuraciones
    {
        public int Codigo { get; set; }
        public Nullable<double> AumentoFinanciacion { get; set; }
        public Nullable<int> Tiempo { get; set; }
        public Nullable<double> IVA { get; set; }
        public Nullable<double> Recargo { get; set; }
        public Nullable<double> MontoMinorista { get; set; }
        public Nullable<double> MontoMayorista { get; set; }
        public Nullable<int> CupoCliente { get; set; }
        public string Sucursal_pricipal { get; set; }
    }
}
