//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Detalle_Bajas
    {
        public int Codigo { get; set; }
        public int Baja { get; set; }
        public string Motivo { get; set; }
        public string Producto { get; set; }
        public int Cantidad { get; set; }
    }
}
