//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_DetalleTranslados
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public string ProductoSucursal { get; set; }
        public double Aumento { get; set; }
        public int Translado { get; set; }
    
        public virtual Translados Translados { get; set; }
    }
}
