//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Proveedores()
        {
            this.Tb_Entradas = new HashSet<Tb_Entradas>();
        }
    
        public int Identificacion { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public int Tipo_Documento { get; set; }
        public string Direccion { get; set; }
        public int Nit { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Empresa { get; set; }
        public string Estado { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Entradas> Tb_Entradas { get; set; }
        public virtual Tb_Tipo_Documento Tb_Tipo_Documento { get; set; }
    }
}
