//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Post
    {
        public int Codigo { get; set; }
        public string Resolucion { get; set; }
        public string Sucursal { get; set; }
        public Nullable<int> Num_actual { get; set; }
    
        public virtual Tb_Sucursales Tb_Sucursales { get; set; }
    }
}
