//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Usuarios()
        {
            this.Tb_Recuperar_contraseña = new HashSet<Tb_Recuperar_contraseña>();
        }
    
        public long Identificacion { get; set; }
        public int Tipo_Documento { get; set; }
        public string Sucursal { get; set; }
        public string Nombre1 { get; set; }
        public string Nombre2 { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Contraseña { get; set; }
        public string Email { get; set; }
        public int Rol { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Recuperar_contraseña> Tb_Recuperar_contraseña { get; set; }
        public virtual Tb_Rol_Usuarios Tb_Rol_Usuarios { get; set; }
        public virtual Tb_Sucursales Tb_Sucursales { get; set; }
        public virtual Tb_Tipo_Documento Tb_Tipo_Documento { get; set; }
    }
}
