//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Translados()
        {
            this.Tb_DetalleTranslados = new HashSet<Tb_DetalleTranslados>();
        }
    
        public int Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Sucursal_origen { get; set; }
        public string Sucursal_Destino { get; set; }
        public double Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DetalleTranslados> Tb_DetalleTranslados { get; set; }
        public virtual Tb_Sucursales Tb_Sucursales { get; set; }
    }
}
