//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_AbonosCuotas
    {
        public int Id { get; set; }
        public int Cuotas { get; set; }
        public System.DateTime FechaAbono { get; set; }
        public double ValorAbono { get; set; }
        public Nullable<double> Recargo { get; set; }
    
        public virtual Tb_Cuotas Tb_Cuotas { get; set; }
    }
}
