//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Detalle_Producto_Sucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Detalle_Producto_Sucursal()
        {
            this.Tb_Detalle_Entrada = new HashSet<Tb_Detalle_Entrada>();
            this.Tb_DetalleTranslados = new HashSet<Tb_DetalleTranslados>();
            this.Tb_DetalleVenta = new HashSet<Tb_DetalleVenta>();
        }
    
        public string codigo_detalle { get; set; }
        public int Stock_Minimo { get; set; }
        public int Stock_Maximo { get; set; }
        public double Valor_Venta { get; set; }
        public double Valor_Mayor { get; set; }
        public Nullable<double> Valor_Especial { get; set; }
        public int Cantidad { get; set; }
        public string Producto { get; set; }
        public string Sucursal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Detalle_Entrada> Tb_Detalle_Entrada { get; set; }
        public virtual Tb_Productos Tb_Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DetalleTranslados> Tb_DetalleTranslados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DetalleVenta> Tb_DetalleVenta { get; set; }
        public virtual Tb_Sucursales Tb_Sucursales { get; set; }
    }
}
