//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Entradas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Entradas()
        {
            this.Tb_Detalle_Entrada = new HashSet<Tb_Detalle_Entrada>();
        }
    
        public int Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Total { get; set; }
        public string Estado { get; set; }
        public string Sucursal { get; set; }
        public int Proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Detalle_Entrada> Tb_Detalle_Entrada { get; set; }
        public virtual Tb_Proveedores Tb_Proveedores { get; set; }
        public virtual Tb_Sucursales Tb_Sucursales { get; set; }
    }
}
