//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Productos()
        {
            this.Tb_Detalle_Producto_Sucursal = new HashSet<Tb_Detalle_Producto_Sucursal>();
        }
    
        public string Codigo_producto { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public string Tipo_Producto { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Detalle_Producto_Sucursal> Tb_Detalle_Producto_Sucursal { get; set; }
        public virtual Tb_Tipo_Producto Tb_Tipo_Producto { get; set; }
    }
}
