//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Sucursales()
        {
            this.Tb_Detalle_Entrada = new HashSet<Tb_Detalle_Entrada>();
            this.Tb_Detalle_Producto_Sucursal = new HashSet<Tb_Detalle_Producto_Sucursal>();
            this.Tb_DetalleTranslados = new HashSet<Tb_DetalleTranslados>();
            this.Tb_DetalleTranslados1 = new HashSet<Tb_DetalleTranslados>();
            this.Tb_Dian = new HashSet<Tb_Dian>();
            this.Tb_Entradas = new HashSet<Tb_Entradas>();
            this.Tb_Post = new HashSet<Tb_Post>();
            this.Tb_Usuarios = new HashSet<Tb_Usuarios>();
            this.Tb_ventas = new HashSet<Tb_ventas>();
        }
    
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Apodo { get; set; }
        public string Prefijo { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string NIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Detalle_Entrada> Tb_Detalle_Entrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Detalle_Producto_Sucursal> Tb_Detalle_Producto_Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DetalleTranslados> Tb_DetalleTranslados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DetalleTranslados> Tb_DetalleTranslados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Dian> Tb_Dian { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Entradas> Tb_Entradas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Post> Tb_Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Usuarios> Tb_Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ventas> Tb_ventas { get; set; }
    }
}
