//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ventas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_ventas()
        {
            this.Tb_Creditos = new HashSet<Tb_Creditos>();
            this.Tb_DetalleVenta = new HashSet<Tb_DetalleVenta>();
            this.Tb_Financiacion = new HashSet<Tb_Financiacion>();
        }
    
        public int Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Total { get; set; }
        public double iva { get; set; }
        public int Cliente { get; set; }
        public string Sucursal { get; set; }
    
        public virtual Tb_Clientes Tb_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Creditos> Tb_Creditos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_DetalleVenta> Tb_DetalleVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Financiacion> Tb_Financiacion { get; set; }
        public virtual Tb_Sucursales Tb_Sucursales { get; set; }
    }
}
